sudo: required
language: python
python:
  - '3.5'
cache: pip
before_install:
  - chmod +x test/run_tests.py
  - chmod +x test/test_sample.py
install:
  - pip install -r requirements.txt
script:
  - python test/run_tests.py
branches:
  only:
    - master
    - dev
    - ken-dev