sudo: required
language: python
python:
  - '3.5'
cache: pip
before_install:
  - chmod +x robot_data_visualizer/test/run_tests.py
  - chmod +x robot_data_visualizer/test/test_data_loader.py
  - chmod +x robot_data_visualizer/test/test_data_manager.py
install:
  - pip install -r requirements.txt
script:
  - python robot_data_visualizer/test/run_tests.py
branches:
  only:
    - master
